// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANB4DCntrgdCN-ybwP_XnTfL6aSpZXBgE',
    appId: '1:490641957402:android:8e89756d1f9eefcb4be7a3',
    messagingSenderId: '490641957402',
    projectId: 'hometek-d4f7f',
    databaseURL: 'https://hometek-d4f7f.firebaseio.com',
    storageBucket: 'hometek-d4f7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5HBlf9fk0tvt_tjmnLpXCUsNGX3laaws',
    appId: '1:490641957402:ios:ad153931dab18cd34be7a3',
    messagingSenderId: '490641957402',
    projectId: 'hometek-d4f7f',
    databaseURL: 'https://hometek-d4f7f.firebaseio.com',
    storageBucket: 'hometek-d4f7f.appspot.com',
    iosClientId: '490641957402-saq91ubirpinmc66v3iedm4v030ql3lu.apps.googleusercontent.com',
    iosBundleId: 'com.intellex.hometek.smartHome',
  );
}
